{{- if .Values.metricsClient.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "videocall.componentFullname" (dict "root" . "component" "metrics-client") }}
  labels:
    {{- include "videocall.labels" (dict "root" . "component" "metrics-client") | nindent 4 }}
spec:
  type: {{ .Values.metricsClient.service.type }}
  ports:
    - port: {{ .Values.metricsClient.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "videocall.selectorLabels" (dict "root" . "component" "metrics-client") | nindent 4 }}
{{- end }}

