{{- if .Values.metricsClient.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videocall.componentFullname" (dict "root" . "component" "metrics-client") }}
  labels:
    {{- include "videocall.labels" (dict "root" . "component" "metrics-client") | nindent 4 }}
spec:
  replicas: {{ .Values.metricsClient.replicaCount }}
  selector:
    matchLabels:
      {{- include "videocall.selectorLabels" (dict "root" . "component" "metrics-client") | nindent 6 }}
  template:
    metadata:
      {{- with .Values.metricsClient.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "videocall.selectorLabels" (dict "root" . "component" "metrics-client") | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.metricsClient.podSecurityContext | nindent 8 }}
      containers:
        - name: metrics-client
          securityContext:
            {{- toYaml .Values.metricsClient.securityContext | nindent 12 }}
          image: "{{ .Values.metricsClient.image.repository }}:{{ .Values.metricsClient.image.tag }}"
          imagePullPolicy: {{ .Values.metricsClient.image.pullPolicy }}
          command: {{ .Values.metricsClient.command }}
          workingDir: {{ .Values.metricsClient.workingDir }}
          env:
            {{- toYaml .Values.metricsClient.env | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.metricsClient.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.metricsClient.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.metricsClient.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.metricsClient.resources | nindent 12 }}
      {{- with .Values.metricsClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metricsClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metricsClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

