{{- if and .Values.website.enabled .Values.website.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "videocall.componentFullname" (dict "root" . "component" "website") }}
  labels:
    {{- include "videocall.labels" (dict "root" . "component" "website") | nindent 4 }}
  {{- with .Values.website.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.website.ingress.className }}
  ingressClassName: {{ .Values.website.ingress.className }}
  {{- end }}
  {{- if .Values.website.ingress.tls }}
  tls:
    {{- range .Values.website.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.website.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port.number }}
          {{- end }}
    {{- end }}
{{- end }}

