{{- if .Values.website.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.service.name | default (include "videocall.componentFullname" (dict "root" . "component" "website")) }}
  labels:
    {{- include "videocall.labels" (dict "root" . "component" "website") | nindent 4 }}
spec:
  type: {{ .Values.website.service.type }}
  ports:
    - port: {{ .Values.website.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "videocall.selectorLabels" (dict "root" . "component" "website") | nindent 4 }}
{{- end }}

