[package]
name = "videocall-nokhwa-core"
version = "0.1.8"
authors = ["l1npengtul <l1npengtul@protonmail.com>", "Dario Lencina <dario@securityunion.dev>"]
edition = "2021"
description = "Core type definitions for nokhwa"
keywords = ["camera", "webcam", "capture", "cross-platform"]
license = "Apache-2.0"
homepage = "https://github.com/security-union/videocall-rs"
repository = "https://github.com/security-union/videocall-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
serialize = ["serde"]
wgpu-types = ["wgpu"]
mjpeg = ["mozjpeg"]
opencv-mat = ["opencv", "opencv/clang-runtime", "bytemuck"]
docs-features = ["serialize", "wgpu-types", "mjpeg"]
test-fail-warnings = []


[dependencies]
thiserror = "2.0"
bytes = "1.3"

[dependencies.image]
version = "0.25"
default-features = false

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[dependencies.wgpu]
version = "23"
optional = true

[dependencies.opencv]
version = "0.93"
optional = true

[dependencies.bytemuck]
version = "1"
optional = true

[dependencies.mozjpeg]
version = "0.10"
optional = true

[package.metadata.docs.rs]
features = ["docs-features"]

[dev-dependencies]
mozjpeg = "0.10.13"
