[workspace]
allow_dirty = false
pr_branch_prefix = "release-plz-"
pr_name = "New Release v{{ version }}"
pr_labels = ["release"]
publish_allow_dirty = false
publish_timeout = "10m"
# dependencies_update = false  # if you want to disable dependencies update
# changelog_level = "workspace"  # to disable changelogs set it to 'off'
git_release_enable = true  # enable release creation on Github/Gitlab

[[package]]
name = "videocall-client"
publish = true
changelog_update = true
git_release_enable = true

[[package]]
name = "videocall-types"
publish = true
changelog_update = true
git_release_enable = true

[[package]]
name = "bot"
publish = false
changelog_update = false
git_release_enable = false
release = false

[[package]]
name = "videocall-api"
publish = false
changelog_update = false
git_release_enable = false
release = false


[changelog]
protect_breaking_commits = true