apiVersion: v2
name: matomo-us-east
version: 0.1.0
description: Matomo analytics for US East region

dependencies:
  - name: matomo
    version: 10.0.25
    repository: https://charts.bitnami.com/bitnami 