apiVersion: v1
kind: Service
metadata:
  name: {{ include "meeting-api.fullname" . }}
  labels:
    {{- include "meeting-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "meeting-api.selectorLabels" . | nindent 4 }}
