[package]
name = "bot"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
tokio-tungstenite = "0.19.0"
serde = "1.0.130"
serde_json = "1.0.72"
rand = "0.8.5"
futures = "0.3.16"

[dependencies.url]
version = "2.3.1"