[package]
name = "bot"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] }
serde = "1.0.130"
serde_json = "1.0.72"
rand = "0.8.5"
futures = "0.3.16"
videocall-types = { path= "../videocall-types"}
protobuf = "=3.7.1"
chrono = "0.4.25"
dotenv = "0.15.0"

[dependencies.url]
version = "2.3.1"
