apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}-ws-api
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wsApi.service.type }}
  ports:
    - port: {{ .Values.wsApi.service.port }}
      targetPort: 8080
      protocol: TCP
      name: wt-api
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
