apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}-wt-api-lb
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
  {{- if .Values.wtApi.loadBalancerAnnotations}}
  annotations:
  {{- range $key, $value := .Values.wtApi.loadBalancerAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: UDP
      port: 4433
      targetPort: 4433
      name: wt-api
    - protocol: UDP
      port: 4434
      targetPort: 4434
      name: wt-api-debug
