apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}-wt-api-lb
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
  {{- if .Values.wtApi.loadBalancerAnnotations}}
  annotations:
  {{- range $key, $value := .Values.wtApi.loadBalancerAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: wt-api-health
    - protocol: UDP
      port: 443
      targetPort: 443
      name: wt-api
